### PR TITLE
Update allachivcoin.lua

### PR DESCRIPTION
**Pull request by Fivever**

### CODE REVIEW

**Comment by Lavax7** [comment]
There is no need to buff some upgrades by *2.
If you want to have stronger upgrades just reduce the cost of the upgrades in the mod config menu in the game.

**Comment by Fivever** [comment]
Sorry for that. For example, if I want to upgrade to 5% crit rate, it requires 7 achievement points, and upgrading to 15% crit rate requires 21 achievement points. At this time, upgrading from 15% crit rate to 20% crit rate needs 9 achievement points. When I reconnect to the game, the required achievement points become 8 points. Similarly, if I need 11 achievement points to upgrade, it will become 9 achievement points after reconnecting. That's why I thought it needs double the cost on function allachivcoin:OnLoad.

**Comment by Lavax7** [comment]
Oh indeed, I looked at the other code and there is also a *2, seems like I forgot it there.
Thank you!

**Comment by Fivever** [comment]
No problem.

**Pull request merged**
